site_name: SmartBench Documentation

theme:
  name: material
  logo: sb-white.png
  favicon: favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Renaissance:
      - Overview: renaissance/index.md
      - FAQ: renaissance/faq.md
      - Assembly:
          - Overview: renaissance/assembly/index.md
          - Assembly Export: renaissance/assembly/assembly-export.md
          - Assembly Links: renaissance/assembly/assembly-links.md
          - Component Share: renaissance/assembly/component-share.md
          - Assembly Configured Properties: renaissance/assembly/configured-properties.md
      - Part:
          - Overview: renaissance/part/index.md
          - Find and Replace: renaissance/part/find-and-replace.md
          - Image Cube: renaissance/part/image-cube.md
          - Part Configured Properties: renaissance/part/configured-properties.md
          - Multiface DXF: renaissance/part/multiface-dxf.md
          - Lock Configuration: renaissance/part/lock-configuration.md
          - Duplicate Feature: renaissance/part/duplicate-feature.md

      - Drawing:
          - Overview: renaissance/drawing/index.md
          - Configured Drawings: renaissance/drawing/configured-drawings.md
          - Magic Drawings: renaissance/drawing/magic-drawings.md
      - All:
          - Overview: renaissance/all/index.md
          - Release Export: renaissance/all/release-export.md
          - Release Package Automation: renaissance/all/release-package-automation.md
          - Publication Updater: renaissance/all/publication-updater.md
          - Link Tab: renaissance/all/link-tab.md
          - Standard Content Metadata: renaissance/all/standard-content-metadata.md
  - fs.place:
      - Overview: fs-place/index.md
  - Kestrel:
      - Overview: kestrel/index.md
      - Kestrel Portal: kestrel/KestrelPortal.md
      - Settings: kestrel/Settings.md
      - Macro: kestrel/solidworks.md
      - Runfile: kestrel/Runfile.md
      - Metadata Files: kestrel/MetadataFiles.md
      - Changelog: kestrel/changelog.md
  - SmartLink:
      - Overview: smart-link/index.md
